export const HTTP_CALL_BEGIN = "HTTP_CALL_BEGIN";
export const HTTP_CALL_END = "HTTP_CALL_END";

// Auth
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";

